AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  HelloApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "hello-api-${Stage}"
      StageName: !Ref Stage

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "hello-lambda-${Stage}"
      Runtime: python3.12
      Handler: src/handler.lambda_handler
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref HelloApi
            Path: /hello
            Method: GET

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${HelloApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
